# Generated by Django 5.1.4 on 2025-01-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Autor(A):')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia do Autor(a):')),
                ('aniversario', models.DateField(verbose_name='Data de Nascimento:')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade:')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização:'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação:'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição:'),
        ),
    ]
