# Generated by Django 5.1.4 on 2025-01-06 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_autor_alter_categoria_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Coleção:')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição:')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação:')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização:')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização:'),
        ),
        migrations.AddField(
            model_name='autor',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação:'),
            preserve_default=False,
        ),
    ]
