# Generated by Django 5.1.4 on 2025-01-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_livro_sinopse_alter_livro_autor_alter_livro_colecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='is_reservado',
            field=models.BooleanField(default=False),
        ),
    ]
